### ISSUE TITLE
Node12 deprecated

### ISSUE THREAD

**Issue by luiz-firework** [chetan/git-restore-mtime-action#19]
Hi! thanks a lot for this lib. We're starting to get notified by GH actions that node12 is soon to be deprecated. Is it possible to change it to node16?

**Comment by chetan** [comment]
@luiz-firework just pushed a new revision, v1.2 (v1 tag also updated). No other changes in this release. Let me know if you still see an issue. Thanks for reporting!

**Comment by luiz-firework** [comment]
thanks!
